version: "3"

services:
    nginx:
        image: nginx:latest
        container_name: "${PROJECT_NAME}_nginx"
        ports:
            - "80:80"
        volumes:
            - ./src:/home/docker/public
            - ./src/assets:/home/docker/media/assets
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - django

    django:
        build: .
        hostname: "${PROJECT_NAME}_django"
        container_name: "${PROJECT_NAME}_django"
        command: bash -c "sudo gunicorn --reload ${PROJECT_NAME}.wsgi -b 0.0.0.0:80"
        expose:
            - 80
        volumes:
            - ./src:/home/docker/public
            - ./src/assets:/home/docker/media/assets
        links:
            - postgresql:postgresql
        depends_on:
            - postgresql
        environment:
            - C_FORCE_ROOT=false
            - DJANGO_SETTINGS_MODULE=urbvan.settings.local

    postgresql:
        image: postgres:10.6
        hostname: "${PROJECT_NAME}_db"
        container_name: "${PROJECT_NAME}_db"
        environment:
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_DB: "${DB_NAME}"
        volumes:
            - db:/var/lib/postgresql/data

volumes:
      db: